### ISSUE TITLE
LRG vs. LRG_1PASS vs. LRG_2PASS

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#432]
We currently have a bunch of LRG bits:
```
desi_mask:
    - [LRG,         0, "LRG", {obsconditions: DARK}]
    - [LRG_1PASS,   3, "LRG observed in 1st pass", {obsconditions: DARK}]
    - [LRG_2PASS,   4, "LRG observed in 2nd pass", {obsconditions: DARK}]
    - [LRG_NORTH,   8, "LRG from Bok/Mosaic data", {obsconditions: DARK}]
    - [LRG_SOUTH,   16, "LRG from DECam data", {obsconditions: DARK}]
    - [LRG_1PASS_NORTH,  24, "LRG observed in 1st pass from Bok/Mosaic", {obsconditions: DARK}]
    - [LRG_2PASS_NORTH,  25, "LRG observed in 2nd pass from Bok/Mosaic", {obsconditions: DARK}]
    - [LRG_1PASS_SOUTH,  28, "LRG observed in 1st pass from DECam", {obsconditions: DARK}]
    - [LRG_2PASS_SOUTH,  29, "LRG observed in 2nd pass from DECam", {obsconditions: DARK}]
...
numobs:
    desi_mask:
        LRG: 2
        LRG_1PASS: 1
        LRG_2PASS: 2
...
```

Do we really need the `LRG`, `LRG_NORTH`, and `LRG_SOUTH` bits, or should we just treat `LRG_1PASS` as different from `LRG_2PASS` without combining them into `LRG` as well?  Maybe it's not so bad, but any numobs / priority logic should be working based on `LRG_1PASS` and `LRG_2PASS` and not the roll-up `LRG` bit.

e.g. related to #429: numobs logic could be simplified by setting `LRG`=0 or 1, and thus letting `LRG1_PASS` and `LRG2_PASS` determine the number of obs instead of special casing `LRG` in the code.

Are the descriptions "LRG observed in 1st pass" and "LRG observed in 2nd pass" correct?  I think they should be "LRG to be observed once" and "LRG to be observed twice".  i.e. the bit name refers to the number of passes in which we would like this LRG to be observed, not which pass it is observed in.

Detail: it's actually the number of *tiles*, not the number of *passes* (i.e. layers); in a region of overlap of tiles in the same pass, an `LRG_2PASS` could be assigned to two tiles on the same tiling pass.  Let's keep the bit names the same anyway.
